language: node_js
node_js:
  - "4"
before_script:
  - npm install -g gulp
script: gulp coverage
addons:
  code_climate:
    repo_token: cc5405333de8292f5f689d20984cdfa9fee1b9c903a96d477c67440fcd9927a6